# -*- coding: utf-8 -*-
"""Data understanding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xs_mzxx4195Mq2hyvYPio16CHrb0JFgE

Loading data into google collab so that I can import it using pandas
"""

from google.colab import files
uploaded = files.upload()

"""## 1. Dataset Preview

Before performing any analysis, we first preview the dataset to confirm that it has been loaded correctly and to get an initial sense of the data structure.

Each row represents a single machine operating instance recorded through multiple sensors.

"""

import pandas as pd
df=pd.read_csv("machine failure data.csv")
df.head()

"""## 2. Dataset Shape

Understanding the size of the dataset helps determine whether it is sufficient for statistical analysis and machine learning.

- Rows represent operational records
- Columns represent sensor measurements and failure labels

"""

df.shape

"""The dataset contains 10,000 observations and 14 features. This size is adequate for exploratory data analysis, statistical modeling, and supervised learning.

## 3. Column Names

This step identifies all available sensor variables and target labels. Early identification of features and targets helps prevent data leakage in later modeling stages.
"""

df.columns

"""The dataset includes environmental sensors, mechanical operating parameters, tool wear information, and multiple failure indicators.

## 4. Data Types

Checking data types ensures that sensor values are correctly interpreted as numerical variables and target labels are appropriately encoded.
"""

df.dtypes

"""All sensor variables are numerical, which is appropriate for statistical and machine learning analysis. Failure indicators are encoded as binary values.

## 5. Missing Values Check

Missing sensor values can indicate data acquisition issues and must be identified before further analysis.
"""

df.isnull().sum()

"""No missing values are present in the dataset, indicating high data quality and reliable sensor acquisition.

## 6. Basic Statistical Summary

A high-level statistical summary provides a preliminary understanding of sensor ranges and operating conditions without performing detailed analysis.
"""

df.describe()

"""The summary statistics show reasonable ranges for temperature, rotational speed, torque, and tool wear, consistent with industrial machine operation.

## 7. Machine Failure Distribution

Understanding the distribution of failures is critical, as predictive maintenance datasets are often highly imbalanced.
"""

df['Machine failure'].value_counts(normalize=True)

"""Machine failures represent a small fraction of total observations, which is expected in real-world industrial systems and must be considered in later modeling stages.

## 9. Physical Interpretation of Sensor Variables

### Air Temperature [K]
Air temperature represents the ambient thermal environment surrounding the machine. It affects cooling efficiency and overall heat dissipation.

### Process Temperature [K]
Process temperature reflects internal machine heating caused by friction, load, and operational stress.

### Rotational Speed [rpm]
Rotational speed indicates mechanical motion intensity. Higher speeds increase frictional heating and centrifugal forces.

### Torque [Nm]
Torque represents mechanical load. High torque values indicate increased stress on machine components.

### Tool Wear [min]
Tool wear measures cumulative usage and degradation. Increased wear leads to higher friction and failure risk.

## 10. Summary

This notebook focused on understanding the dataset structure, sensor variables, and failure labels from both a data science and physics perspective. No preprocessing or modeling was performed to preserve raw data integrity.
"""